# youtube_upload.py
import os
import glob
import pickle
import datetime
from zoneinfo import ZoneInfo

from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request

SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]

# 이 파일(youtube_upload.py)은 shorts_new/src 안에 있고,
# 인증 파일들은 shorts_new/secrets 안에 있음을 기준으로 경로를 계산.
_SRC_DIR = os.path.dirname(os.path.abspath(__file__))
_SECRETS_DIR = os.path.join(_SRC_DIR, "..", "secrets")


def _find_default_client_secrets():
    """secrets 폴더에서 client_secret*.json 패턴의 파일을 자동으로 찾음."""
    candidates = glob.glob(os.path.join(_SECRETS_DIR, "client_secret*.json"))
    if candidates:
        return candidates[0]
    # 못 찾으면 예전 기본 파일명으로 폴백 (에러 메시지에서 바로 원인 파악 가능하도록)
    return os.path.join(_SECRETS_DIR, "client_secrets.json")


# .env 에 YT_CLIENT_SECRETS / YT_TOKEN_FILE 을 직접 넣으면 그 값이 우선 적용됨.
CLIENT_SECRETS_FILE = os.getenv("YT_CLIENT_SECRETS", _find_default_client_secrets())
TOKEN_FILE = os.getenv("YT_TOKEN_FILE", os.path.join(_SECRETS_DIR, "token.pickle"))

KST = ZoneInfo("Asia/Seoul")

# 시간대별 예약 시각 (KST 기준)
# "아침" 은 주말(토/일)에 "출근" 대신 쓰이는 라벨이라 같은 시각으로 매핑.
SCHEDULE_MAP = {
    "출근": {"hour": 8,  "minute": 30},
    "아침": {"hour": 8,  "minute": 30},
    "저녁": {"hour": 18, "minute": 0},
    "자기전": {"hour": 21, "minute": 0},
}


# ────────────────────────────────
# 인증
# ────────────────────────────────
def get_credentials():
    creds = None

    if os.path.exists(TOKEN_FILE):
        with open(TOKEN_FILE, "rb") as f:
            creds = pickle.load(f)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            if not os.path.exists(CLIENT_SECRETS_FILE):
                raise FileNotFoundError(
                    f"클라이언트 시크릿 파일을 찾을 수 없습니다: {CLIENT_SECRETS_FILE}\n"
                    f"secrets 폴더에 client_secret*.json 파일이 있는지, "
                    f"또는 .env 의 YT_CLIENT_SECRETS 값이 올바른지 확인해주세요."
                )
            flow = InstalledAppFlow.from_client_secrets_file(
                CLIENT_SECRETS_FILE, SCOPES
            )
            creds = flow.run_local_server(port=0)

        os.makedirs(os.path.dirname(TOKEN_FILE), exist_ok=True)
        with open(TOKEN_FILE, "wb") as f:
            pickle.dump(creds, f)

    return creds


# ────────────────────────────────
# 예약 시각 계산
# ────────────────────────────────
def get_publish_at(date_str: str, time_type: str) -> str:
    """
    date_str: "2026-04-22"
    time_type: "출근" or "자기전"
    반환: YouTube API용 RFC 3339 문자열 (UTC)
    """
    schedule = SCHEDULE_MAP.get(time_type)
    if not schedule:
        raise ValueError(f"알 수 없는 time_type: {time_type}")

    d = datetime.datetime.strptime(date_str, "%Y-%m-%d").date()

    # KST로 예약 시각 생성
    publish_kst = datetime.datetime(
        d.year, d.month, d.day,
        schedule["hour"], schedule["minute"], 0,
        tzinfo=KST,
    )

    # UTC로 변환 후 RFC 3339 포맷
    publish_utc = publish_kst.astimezone(datetime.timezone.utc)
    return publish_utc.strftime("%Y-%m-%dT%H:%M:%S.000Z")


# ────────────────────────────────
# 설명 텍스트 조립
# ────────────────────────────────
def build_description(date_str: str, verse: str, content: str) -> str:
    short_date = date_str.replace("-", "")[2:]  # "20260422" → "260422"

    fixed_footer = (
        "\n"
        "🙏 함께 묵상해요!\n"
        "1️⃣ 말씀에서 떠오른 생각을 댓글로 나눠주세요\n"
        "2️⃣ '구독'과 '좋아요'로 다음 묵상을 응원해주세요\n"
        "\n"
        "— generated by Edn'pa2 —\n"
        "\n"
        "#Shorts #오늘의말씀 #BibleVerse"
    )

    description = (
        f"🕊️ {short_date} 오늘의 말씀\n"
        f"{verse} {content}\n"
        f"{fixed_footer}"
    )
    return description


# ────────────────────────────────
# 업로드
# ────────────────────────────────
def upload_to_youtube(
    video_path: str,
    title: str,
    description: str,
    date_str: str,
    time_type: str,
) -> str:
    publish_at = get_publish_at(date_str, time_type)
    print(f"[YouTube] 업로드 시작: {video_path}")
    print(f"[YouTube] 예약 공개: {publish_at} (UTC) → KST {SCHEDULE_MAP[time_type]['hour']}시 {SCHEDULE_MAP[time_type]['minute']:02d}분")

    creds = get_credentials()
    youtube = build("youtube", "v3", credentials=creds)

    body = {
        "snippet": {
            "title": title,
            "description": description,
            "categoryId": "22",
            "tags": ["오늘의말씀", "BibleVerse", "Shorts", "성경", "묵상"],
            "defaultLanguage": "ko",
        },
        "status": {
            "privacyStatus": "private",        # 예약은 반드시 private으로 시작
            "publishAt": publish_at,            # ★ 예약 공개 시각
            "selfDeclaredMadeForKids": False,
        },
    }

    media = MediaFileUpload(video_path, chunksize=-1, resumable=True)

    request = youtube.videos().insert(
        part="snippet,status",
        body=body,
        media_body=media,
    )

    response = None
    while response is None:
        status, response = request.next_chunk()
        if status:
            pct = int(status.progress() * 100)
            print(f"[YouTube] 업로드 중... {pct}%")

    video_id = response["id"]
    url = f"https://youtube.com/shorts/{video_id}"
    print(f"[YouTube] 업로드 완료 → {url}")
    sched = SCHEDULE_MAP[time_type]
    ampm = "오전" if sched["hour"] < 12 else "오후"
    hour12 = sched["hour"] if sched["hour"] <= 12 else sched["hour"] - 12
    print(f"[YouTube] 예약 공개 시각: {date_str} {ampm} {hour12}:{sched['minute']:02d} (KST)")
    return video_id
